Unable to init server: Could not connect: Connection refused
Unable to init server: Impossible de se connecterÂ : Connection refused

(model.py:1948944): Gdk-CRITICAL **: 09:31:33.266: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
